language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t cjerochim/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cjerochim/react-test npm test

after_success:
  - docker build -t cjerochim/multi-client ./client
  - docker build -t cjerochim/multi-nginx ./nginx
  - docker build -t cjerochim/multi-server ./server
  - docker build -t cjerochim/multi-worker ./worker
  # Login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push
  - docker push cjerochim/multi-client
  - docker push cjerochim/multi-nginx
  - docker push cjerochim/multi-server
  - docker push cjerochim/multi-worker

deploy:
  provider: elasticbeanstalk
  region: ap-southeast-2
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-ap-southeast-2-635319515320
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
